openapi: 3.2.0
info:
  title: Verifiable API Documentation Facilities API
  description: '# Introduction


    This document contains the official documentation for the latest version of the Verifiable API.'
  version: 26.12.1.962
servers:
- url: https://discovery.verifiable.com/api
  description: Production
- url: https://discovery-staging.verifiable.com/api
  description: Staging
tags:
- name: Facilities
  description: Endpoints related to managing and retrieving Facility data.
paths:
  /facilities:
    post:
      tags:
      - Facilities
      summary: Create a new facility
      description: Creates a new facility that can be used to store information about the facility.
      operationId: CreateFacility
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FacilityRequestModel'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FacilityModel'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '500':
          description: Server Error
      security:
      - Bearer: []
    get:
      tags:
      - Facilities
      summary: List facilities
      description: Returns a page of facilities.
      operationId: ListFacilities
      parameters:
      - name: name
        in: query
        description: If set, the items will be filtered on facilities with the specified name.
        schema:
          type: string
      - name: deactivated
        in: query
        description: If set, the items will be filtered on facilities with the specified deactivated status.
        schema:
          type: boolean
      - name: parentFacilityId
        in: query
        schema:
          type: string
          format: uuid
      - name: sortedBy
        in: query
        description: The property by which the returned data will be sorted.
        schema:
          enum:
          - Id
          - Name
          type: string
      - name: sort
        in: query
        description: If set, the properties and directions the returned data will be sorted by.
        schema:
          type: object
          properties:
            Keys:
              enum:
              - Id
              - Name
              type: string
            Values:
              enum:
              - Asc
              - Desc
              type: string
      - name: offset
        in: query
        description: The offset for the page to start.
        deprecated: true
        schema:
          type: integer
          format: int32
      - name: cursor
        in: query
        description: The cursor to render the page requested. To load the first page send an empty cursor, then the system will generate the cursors to go to the next and/or previous pages automatically.
        schema:
          type: string
      - name: count
        in: query
        description: The number of items to include in a single page.
        schema:
          type: integer
          format: int32
      - name: sortDirection
        in: query
        description: The direction the returned data will be sorted by.
        schema:
          enum:
          - Asc
          - Desc
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FacilityPageModel'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Server Error
      security:
      - Bearer: []
  /facilities/{facilityId}:
    get:
      tags:
      - Facilities
      summary: Get an existing facility
      description: Returns the data for a specific facility.
      operationId: GetFacility
      parameters:
      - name: facilityId
        in: path
        description: Identifier of the facility to get the data for.
        required: true
        schema:
          type: string
          format: uuid
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FacilityModel'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Server Error
      security:
      - Bearer: []
    patch:
      tags:
      - Facilities
      summary: Patch an existing facility
      description: Allows you to change a facility's name or other data properties.
      operationId: PatchFacility
      parameters:
      - name: facilityId
        in: path
        description: Identifier of the facility to patch.
        required: true
        schema:
          type: string
          format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FacilityPatchModel'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FacilityModel'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Server Error
      security:
      - Bearer: []
  /facilities/license-types:
    get:
      tags:
      - Facilities
      summary: List facility license types
      description: Returns a page of facility license types.
      operationId: ListFacilityLicenseTypes
      parameters:
      - name: name
        in: query
        description: If set, the items will be filtered on facility license types with the specified name.
        schema:
          type: string
      - name: sortedBy
        in: query
        description: The property by which the returned data will be sorted.
        schema:
          enum:
          - Id
          - Name
          type: string
      - name: sort
        in: query
        description: If set, the properties and directions the returned data will be sorted by.
        schema:
          type: object
          properties:
            Keys:
              enum:
              - Id
              - Name
              type: string
            Values:
              enum:
              - Asc
              - Desc
              type: string
      - name: offset
        in: query
        description: The offset for the page to start.
        deprecated: true
        schema:
          type: integer
          format: int32
      - name: cursor
        in: query
        description: The cursor to render the page requested. To load the first page send an empty cursor, then the system will generate the cursors to go to the next and/or previous pages automatically.
        schema:
          type: string
      - name: count
        in: query
        description: The number of items to include in a single page.
        schema:
          type: integer
          format: int32
      - name: sortDirection
        in: query
        description: The direction the returned data will be sorted by.
        schema:
          enum:
          - Asc
          - Desc
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FacilityLicenseTypePageModel'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '500':
          description: Server Error
      security:
      - Bearer: []
  /facilities/accreditations:
    get:
      tags:
      - Facilities
      summary: List facility accreditations
      description: Returns a page of facility accreditations.
      operationId: ListFacilityAccreditations
      parameters:
      - name: agencyName
        in: query
        description: If set, the items will be filtered on facility accreditations with the specified agency name.
        schema:
          type: string
      - name: sortedBy
        in: query
        description: The property by which the returned data will be sorted.
        schema:
          enum:
          - Id
          - AgencyName
          type: string
      - name: sort
        in: query
        description: If set, the properties and directions the returned data will be sorted by.
        schema:
          type: object
          properties:
            Keys:
              enum:
              - Id
              - AgencyName
              type: string
            Values:
              enum:
              - Asc
              - Desc
              type: string
      - name: offset
        in: query
        description: The offset for the page to start.
        deprecated: true
        schema:
          type: integer
          format: int32
      - name: cursor
        in: query
        description: The cursor to render the page requested. To load the first page send an empty cursor, then the system will generate the cursors to go to the next and/or previous pages automatically.
        schema:
          type: string
      - name: count
        in: query
        description: The number of items to include in a single page.
        schema:
          type: integer
          format: int32
      - name: sortDirection
        in: query
        description: The direction the returned data will be sorted by.
        schema:
          enum:
          - Asc
          - Desc
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FacilityAccreditationAgencyPageModel'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '500':
          description: Server Error
      security:
      - Bearer: []
  /facilities/medicare-enrollment-types:
    get:
      tags:
      - Facilities
      summary: List facility medicare enrollment types
      description: Returns a page of facility medicare enrollment types.
      operationId: ListFacilityMedicareEnrollmentTypes
      parameters:
      - name: id
        in: query
        description: If set, only items whose Id matches the passed in ID are set. Returns a single matching item.
        schema:
          type: string
          format: uuid
      - name: sortedBy
        in: query
        description: The property by which the returned data will be sorted.
        schema:
          enum:
          - Code
          - Description
          type: string
      - name: sort
        in: query
        description: If set, the properties and directions the returned data will be sorted by.
        schema:
          type: object
          additionalProperties:
            enum:
            - Asc
            - Desc
            type: string
      - name: offset
        in: query
        description: The offset for the page to start.
        deprecated: true
        schema:
          type: integer
          format: int32
      - name: cursor
        in: query
        description: The cursor to render the page requested. To load the first page send an empty cursor, then the system will generate the cursors to go to the next and/or previous pages automatically.
        schema:
          type: string
      - name: count
        in: query
        description: The number of items to include in a single page.
        schema:
          type: integer
          format: int32
      - name: sortDirection
        in: query
        description: The direction the returned data will be sorted by.
        schema:
          enum:
          - Asc
          - Desc
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MedicareEnrollmentTypePageModel'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '500':
          description: Server Error
      security:
      - Bearer: []
  /facilities/taxonomies:
    get:
      tags:
      - Facilities
      summary: List facility taxonomies
      description: Returns a page of facility taxonomies.
      operationId: ListFacilityTaxonomies
      parameters:
      - name: code
        in: query
        description: If set, the items will be filtered on facility taxonomies with the specified code, even if partially equals. Case insensitive.
        schema:
          type: string
      - name: name
        in: query
        description: If set, the items will be filtered on facility taxonomies with the specified name, even if partially equals. Case insensitive.
        schema:
          type: string
      - name: sortedBy
        in: query
        description: The property by which the returned data will be sorted.
        schema:
          enum:
          - Id
          - Code
          type: string
      - name: sort
        in: query
        description: If set, the properties and directions the returned data will be sorted by.
        schema:
          type: object
          properties:
            Keys:
              enum:
              - Id
              - Code
              type: string
            Values:
              enum:
              - Asc
              - Desc
              type: string
      - name: offset
        in: query
        description: The offset for the page to start.
        deprecated: true
        schema:
          type: integer
          format: int32
      - name: cursor
        in: query
        description: The cursor to render the page requested. To load the first page send an empty cursor, then the system will generate the cursors to go to the next and/or previous pages automatically.
        schema:
          type: string
      - name: count
        in: query
        description: The number of items to include in a single page.
        schema:
          type: integer
          format: int32
      - name: sortDirection
        in: query
        description: The direction the returned data will be sorted by.
        schema:
          enum:
          - Asc
          - Desc
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FacilityTaxonomyPageModel'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '500':
          description: Server Error
      security:
      - Bearer: []
components:
  schemas:
    FacilityLicenseTypePageModel:
      type: object
      properties:
        sort:
          type: object
          properties:
            Keys:
              enum:
              - Id
              - Name
              type: string
            Values:
              enum:
              - Asc
              - Desc
              type: string
          description: The properties and directions the data is sorted by.
        previousCursor:
          type: string
          description: The value to use for `cursor` to get to the previous paginated page. `null` will be returned if it's the first page.
        nextCursor:
          type: string
          description: The value to use for `cursor` to get to the next paginated page. `null` will be returned if it's the last page.
        nextOffset:
          type: integer
          description: The value to use for `offset` to get the next page following the current page or `null` if this page is the last.
          format: int32
          deprecated: true
        pageSize:
          type: integer
          description: The maximum number of items included in this page.
          format: int32
        count:
          type: integer
          description: The number of items in this page.
          format: int32
        totalCount:
          type: integer
          description: The total number of items in all pages combined.
          format: int32
        items:
          type: array
          items:
            $ref: '#/components/schemas/FacilityLicenseTypeModel'
          description: The facility license types in the current page.
        sortedBy:
          enum:
          - Id
          - Name
          type: string
          description: The property by which the data is sorted.
        sortDirection:
          enum:
          - Asc
          - Desc
          type: string
          description: The direction in which the data is sorted.
      additionalProperties: false
      example:
        previousCursor: string
        nextCursor: string
        nextOffset: 0
        pageSize: 0
        count: 0
        totalCount: 0
        items:
        - id: 497f6eca-6276-4993-bfeb-53cbbbba6f08
          name: string
        sort:
          Id: Asc
    MedicareEnrollmentTypePageModel:
      type: object
      properties:
        sort:
          type:
          - object
          - 'null'
          additionalProperties:
            enum:
            - Asc
            - Desc
            type: string
        previousCursor:
          type:
          - string
          - 'null'
        nextCursor:
          type:
          - string
          - 'null'
        nextOffset:
          type:
          - integer
          - 'null'
          format: int32
        pageSize:
          type: integer
          format: int32
        count:
          type: integer
          format: int32
        totalCount:
          type:
          - integer
          - 'null'
          format: int32
        items:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/MedicareEnrollmentTypeModel'
        sortedBy:
          enum:
          - Code
          - Description
          type:
          - string
          - 'null'
        sortDirection:
          enum:
          - Asc
          - Desc
          type:
          - string
          - 'null'
      additionalProperties: false
    FacilityLicenseTypeModel:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type:
          - string
          - 'null'
      additionalProperties: false
    FacilityModel:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
          description: The name of this facility.
        createdAt:
          type: string
          description: Timestamp when this facility was created.
          format: date-time
        deactivated:
          type: boolean
          description: If set, the facility is deactivated.
        parentFacilityId:
          type: string
          format: uuid
        dba:
          type: string
          description: The DBA of this facility.
        addressLine1:
          type: string
          description: The street address of this facility.
        addressLine2:
          type: string
          description: The secondary address information of this facility.
        city:
          type: string
          description: The city in which the facility address is located.
        state:
          enum:
          - AL
          - AK
          - AZ
          - AR
          - CA
          - CO
          - CT
          - DE
          - DC
          - FL
          - GA
          - HI
          - ID
          - IL
          - IN
          - IA
          - KS
          - KY
          - LA
          - ME
          - MD
          - MA
          - MI
          - MN
          - MS
          - MO
          - MT
          - NE
          - NV
          - NH
          - NJ
          - NM
          - NY
          - NC
          - ND
          - OH
          - OK
          - OR
          - PA
          - RI
          - SC
          - SD
          - TN
          - TX
          - UT
          - VT
          - VA
          - WA
          - WV
          - WI
          - WY
          - AS
          - GU
          - MP
          - PR
          - VI
          type: string
          description: The state in which the facility address is located.
        zipCode:
          type: string
          description: The postal code associated with the facility address.
        phoneNumber:
          type: string
          description: Phone number associated with the facility.
        faxNumber:
          type: string
          description: Fax number associated with the facility.
        groupTaxId:
          type: string
          description: The group tax id associated with the facility.
        facilityTaxId:
          type: string
          description: The tax id associated with the facility.
        contactName:
          type: string
          description: The contact name associated with the facility.
        contactEmail:
          type: string
          description: The contact email associated with the facility.
        medicarePartANumber:
          type: string
        medicarePartBNumber:
          type: string
        medicaidNumber:
          type: string
      additionalProperties: false
    FacilityAccreditationAgencyPageModel:
      type: object
      properties:
        sort:
          type: object
          properties:
            Keys:
              enum:
              - Id
              - AgencyName
              type: string
            Values:
              enum:
              - Asc
              - Desc
              type: string
          description: The properties and directions the data is sorted by.
        previousCursor:
          type: string
          description: The value to use for `cursor` to get to the previous paginated page. `null` will be returned if it's the first page.
        nextCursor:
          type: string
          description: The value to use for `cursor` to get to the next paginated page. `null` will be returned if it's the last page.
        nextOffset:
          type: integer
          description: The value to use for `offset` to get the next page following the current page or `null` if this page is the last.
          format: int32
          deprecated: true
        pageSize:
          type: integer
          description: The maximum number of items included in this page.
          format: int32
        count:
          type: integer
          description: The number of items in this page.
          format: int32
        totalCount:
          type: integer
          description: The total number of items in all pages combined.
          format: int32
        items:
          type: array
          items:
            $ref: '#/components/schemas/FacilityAccreditationAgencyModel'
          description: The facility accreditations in the current page.
        sortedBy:
          enum:
          - Id
          - AgencyName
          type: string
          description: The property by which the data is sorted.
        sortDirection:
          enum:
          - Asc
          - Desc
          type: string
          description: The direction in which the data is sorted.
      additionalProperties: false
      example:
        previousCursor: string
        nextCursor: string
        nextOffset: 0
        pageSize: 0
        count: 0
        totalCount: 0
        items:
        - id: 497f6eca-6276-4993-bfeb-53cbbbba6f08
          agencyName: string
          programs:
          - id: 497f6eca-6276-4993-bfeb-53cbbbba6f08
            programName: string
        sort:
          Id: Asc
    FacilityRequestModel:
      required:
      - addressLine1
      - city
      - name
      - state
      - zipCode
      type: object
      properties:
        name:
          minLength: 1
          type: string
          description: The name of this facility.
        parentFacilityId:
          type: string
          format: uuid
        dba:
          type: string
          description: The DBA of this facility.
        addressLine1:
          minLength: 1
          type: string
          description: The street address of this facility.
        addressLine2:
          type: string
          description: The secondary address information of this facility.
        city:
          minLength: 1
          type: string
          description: The city in which the facility address is located.
        state:
          enum:
          - AL
          - AK
          - AZ
          - AR
          - CA
          - CO
          - CT
          - DE
          - DC
          - FL
          - GA
          - HI
          - ID
          - IL
          - IN
          - IA
          - KS
          - KY
          - LA
          - ME
          - MD
          - MA
          - MI
          - MN
          - MS
          - MO
          - MT
          - NE
          - NV
          - NH
          - NJ
          - NM
          - NY
          - NC
          - ND
          - OH
          - OK
          - OR
          - PA
          - RI
          - SC
          - SD
          - TN
          - TX
          - UT
          - VT
          - VA
          - WA
          - WV
          - WI
          - WY
          - AS
          - GU
          - MP
          - PR
          - VI
          type: string
          description: The state in which the facility address is located.
        zipCode:
          minLength: 1
          type: string
          description: The postal code associated with the facility address.
        phoneNumber:
          type: string
          description: Phone number associated with the facility.
        faxNumber:
          type: string
          description: Fax number associated with the facility.
        groupTaxId:
          type: string
          description: The group tax id associated with the facility.
        facilityTaxId:
          type: string
          description: The tax id associated with the facility.
        contactName:
          type: string
          description: The contact name associated with the facility.
        contactEmail:
          type: string
          description: The contact email associated with the facility.
        medicarePartANumber:
          type: string
        medicarePartBNumber:
          type: string
        medicaidNumber:
          type: string
      additionalProperties: false
    FacilityAccreditationAgencyModel:
      type: object
      properties:
        id:
          type: string
          format: uuid
        agencyName:
          type:
          - string
          - 'null'
        programs:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/FacilityAccreditationProgramModel'
      additionalProperties: false
    FacilityPatchModel:
      type: object
      properties:
        name:
          type: string
          description: If set, the facility's `name` will be updated with this value.
        deactivated:
          type: boolean
          description: If set to true, the facility will be deactivated. If set to false, the facility will be activated.
        parentFacilityId:
          type: string
          format: uuid
        dba:
          type: string
          description: If set, the facility's `DBA` will be updated with this value.
        addressLine1:
          type: string
          description: If set, the facility's `street address` will be updated with this value.
        addressLine2:
          type: string
          description: If set, the facility's `secondary address` will be updated with this value.
        city:
          type: string
          description: If set, the facility's `city` will be updated with this value.
        state:
          enum:
          - AL
          - AK
          - AZ
          - AR
          - CA
          - CO
          - CT
          - DE
          - DC
          - FL
          - GA
          - HI
          - ID
          - IL
          - IN
          - IA
          - KS
          - KY
          - LA
          - ME
          - MD
          - MA
          - MI
          - MN
          - MS
          - MO
          - MT
          - NE
          - NV
          - NH
          - NJ
          - NM
          - NY
          - NC
          - ND
          - OH
          - OK
          - OR
          - PA
          - RI
          - SC
          - SD
          - TN
          - TX
          - UT
          - VT
          - VA
          - WA
          - WV
          - WI
          - WY
          - AS
          - GU
          - MP
          - PR
          - VI
          type: string
          description: If set, the facility's `state` will be updated with this value.
        zipCode:
          type: string
          description: If set, the facility's `zip code` will be updated with this value.
        phoneNumber:
          type: string
          description: If set, the facility's `phone number` will be updated with this value.
        faxNumber:
          type: string
          description: If set, the facility's `fax number` will be updated with this value.
        groupTaxId:
          type: string
          description: If set, the facility's `group tax id` will be updated with this value.
        facilityTaxId:
          type: string
          description: If set, the facility's `facility tax id` will be updated with this value.
        contactName:
          type: string
          description: If set, the facility's `contact name` will be updated with this value.
        contactEmail:
          type: string
          description: If set, the facility's `contact email` will be updated with this value.
        medicarePartANumber:
          type: string
        medicarePartBNumber:
          type: string
        medicaidNumber:
          type: string
      additionalProperties: false
    FacilityTaxonomyModel:
      type: object
      properties:
        id:
          type: string
          format: uuid
        code:
          type:
          - string
          - 'null'
        name:
          type:
          - string
          - 'null'
      additionalProperties: false
    FacilityAccreditationProgramModel:
      type: object
      properties:
        id:
          type: string
          format: uuid
        programName:
          type:
          - string
          - 'null'
      additionalProperties: false
    MedicareEnrollmentTypeModel:
      type: object
      properties:
        id:
          type: string
          format: uuid
        code:
          type:
          - string
          - 'null'
        description:
          type:
          - string
          - 'null'
      additionalProperties: false
    FacilityTaxonomyPageModel:
      type: object
      properties:
        sort:
          type: object
          properties:
            Keys:
              enum:
              - Id
              - Code
              type: string
            Values:
              enum:
              - Asc
              - Desc
              type: string
          description: The properties and directions the data is sorted by.
        previousCursor:
          type: string
          description: The value to use for `cursor` to get to the previous paginated page. `null` will be returned if it's the first page.
        nextCursor:
          type: string
          description: The value to use for `cursor` to get to the next paginated page. `null` will be returned if it's the last page.
        nextOffset:
          type: integer
          description: The value to use for `offset` to get the next page following the current page or `null` if this page is the last.
          format: int32
          deprecated: true
        pageSize:
          type: integer
          description: The maximum number of items included in this page.
          format: int32
        count:
          type: integer
          description: The number of items in this page.
          format: int32
        totalCount:
          type: integer
          description: The total number of items in all pages combined.
          format: int32
        items:
          type: array
          items:
            $ref: '#/components/schemas/FacilityTaxonomyModel'
          description: The facility taxonomies in the current page.
        sortedBy:
          enum:
          - Id
          - Code
          type: string
          description: The property by which the data is sorted.
        sortDirection:
          enum:
          - Asc
          - Desc
          type: string
          description: The direction in which the data is sorted.
      additionalProperties: false
      example:
        previousCursor: string
        nextCursor: string
        nextOffset: 0
        pageSize: 0
        count: 0
        totalCount: 0
        items:
        - id: 497f6eca-6276-4993-bfeb-53cbbbba6f08
          code: string
          name: string
        sort:
          Code: Asc
    FacilityPageModel:
      type: object
      properties:
        sort:
          type: object
          properties:
            Keys:
              enum:
              - Id
              - Name
              type: string
            Values:
              enum:
              - Asc
              - Desc
              type: string
          description: The properties and directions the data is sorted by.
        previousCursor:
          type: string
          description: The value to use for `cursor` to get to the previous paginated page. `null` will be returned if it's the first page.
        nextCursor:
          type: string
          description: The value to use for `cursor` to get to the next paginated page. `null` will be returned if it's the last page.
        nextOffset:
          type: integer
          description: The value to use for `offset` to get the next page following the current page or `null` if this page is the last.
          format: int32
          deprecated: true
        pageSize:
          type: integer
          description: The maximum number of items included in this page.
          format: int32
        count:
          type: integer
          description: The number of items in this page.
          format: int32
        totalCount:
          type: integer
          description: The total number of items in all pages combined.
          format: int32
        items:
          type: array
          items:
            $ref: '#/components/schemas/FacilityModel'
          description: The facilities in the current page.
        sortedBy:
          enum:
          - Id
          - Name
          type: string
          description: The property by which the data is sorted.
        sortDirection:
          enum:
          - Asc
          - Desc
          type: string
          description: The direction in which the data is sorted.
      additionalProperties: false
      example:
        previousCursor: string
        nextCursor: string
        nextOffset: 0
        pageSize: 0
        count: 0
        totalCount: 0
        items:
        - id: 497f6eca-6276-4993-bfeb-53cbbbba6f08
          name: string
          deactivated: bool
          dba: string
          addressLine1: string
          addressLine2: string
          city: string
          state: enum
          zipCode: string
          phoneNumber: string
          faxNumber: string
          groupTaxId: string
          facilityTaxId: string
          contactName: string
          contactEmail: string
        sortedBy: Id
        sortDirection: Asc
        sort:
          Id: Asc
  securitySchemes:
    Bearer:
      type: http
      description: 'Enter your bearer token in the format: Bearer {your token}'
      scheme: bearer
      bearerFormat: custom
x-tagGroups:
- name: Authentication
  tags:
  - Authentication
- name: Definitions
  tags:
  - Definitions
- name: Providers
  tags:
  - Providers
  - ProvidersInfo
  - ProviderProfiles
  - Notes
  - Files
- name: Facilities
  tags:
  - Facilities
  - FacilitiesInfo
  - FacilitiesSpecialties
- name: Verifications
  tags:
  - Licenses
  - Datasets
  - DEA
  - BoardCertifications
- name: Monitoring
  tags:
  - Monitoring
  - Alerts
- name: Credentialing
  tags:
  - CredentialingRequests
- name: Integrations
  tags:
  - Integrations
  - Webhooks
- name: Audits
  tags:
  - Audit
- name: Account
  tags:
  - Users
- name: Organizations
  tags:
  - Reports
- name: Models
  tags:
  - Dataset Records
  - Webhook Callbacks
